(function(q){function e(b,a){if(null==a)return null;null==a.__id__&&(a.__id__=n++);var d;null==b.hx__closures__?b.hx__closures__={}:d=b.hx__closures__[a.__id__];null==d&&(d=function(){return d.method.apply(d.scope,arguments)},d.scope=b,d.method=a,b.hx__closures__[a.__id__]=d);return d}var a=function(){};a.activate=function(b){a.timeStart=new Date;a.disposables=new p;a.view=new c;null==b?a.enable():b.enabled?a.enable():a.disable()};a.serialize=function(){return{enabled:a.enabled}};a.deactivate=function(){null!=
a.timer&&(a.timer.stop(),a.timer=null);a.view.destroy();a.disposables.dispose()};a.enable=function(){a.enabled=!0;null!=a.commandEnable&&a.commandEnable.dispose();a.disposables.add(a.commandDisable=atom.commands.add("atom-workspace","clock:hide",function(b){a.disable()}));a.timer=new k(1E3);a.timer.run=a.update;a.view.show();a.view.setTime(new Date)};a.disable=function(){a.enabled=!1;null!=a.timer&&(a.timer.stop(),a.timer=null);null!=a.commandDisable&&a.commandDisable.dispose();a.disposables.add(a.commandEnable=
atom.commands.add("atom-workspace","clock:show",function(b){a.enable()}));a.view.hide()};a.update=function(){a.view.setTime(new Date)};a.consumeStatusBar=function(b){b.addRightTile({item:a.view.element,priority:-100})};var g=function(){this.element=window.document.createElement("div");this.element.classList.add("status-bar-clock","inline-block");this.element.style.display="inline-block";this.configChangeListener=atom.config.onDidChange("clock",{},e(this,this.handleConfigChange))};g.prototype={show:function(){this.element.style.display=
"inline-block"},hide:function(){this.element.style.display="none"},destroy:function(){this.configChangeListener.dispose();this.element.remove()},setTime:function(b){},handleConfigChange:function(b){}};var c=function(){g.call(this);this.showSeconds=atom.config.get("clock.seconds");this.format24=atom.config.get("clock.format");this.amPmSuffix=atom.config.get("clock.am_pm_suffix");this.setShowIcon(atom.config.get("clock.icon"));this.element.addEventListener("mouseover",e(this,this.handleMouseOver),!1);
this.element.addEventListener("mouseout",e(this,this.handleMouseOut),!1);this.contextMenu=atom.contextMenu.add({".status-bar-clock":[{label:"Hide",command:"clock:hide"}]})};c.formatTimePart=function(b){return 10>b?"0"+b:null==b?"null":""+b};c.__super__=g;c.prototype=function(b,a){function d(){}d.prototype=b;var c=new d,f;for(f in a)c[f]=a[f];a.toString!==Object.prototype.toString&&(c.toString=a.toString);return c}(g.prototype,{destroy:function(){g.prototype.destroy.call(this);this.element.removeEventListener("mouseover",
e(this,this.handleMouseOver));this.element.removeEventListener("mouseout",e(this,this.handleMouseOut));null!=this.tooltip&&this.tooltip.dispose();this.contextMenu.dispose()},setTime:function(b){var a=b.getHours();!this.format24&&12<a&&(a-=12);a=c.formatTimePart(a)+":"+c.formatTimePart(b.getMinutes());this.showSeconds&&(a+=":"+c.formatTimePart(b.getSeconds()));!this.format24&&this.amPmSuffix&&(a=12<b.getHours()?a+" PM":a+" AM");this.element.textContent=a},handleConfigChange:function(b){b=b.newValue;
this.showSeconds=b.seconds;this.format24=b.format;this.amPmSuffix=b.am_pm_suffix;this.setShowIcon(b.icon);a.enabled&&this.setTime(new Date)},setShowIcon:function(a){a?this.element.classList.add("icon-clock"):this.element.classList.remove("icon-clock")},handleMouseOver:function(b){null!=this.tooltip&&this.tooltip.dispose();b="<div>"+l.dateStr(new Date)+"</div>";b+="<div>This session started: "+m.xTimeAgo(a.timeStart)+"</div>";this.tooltip=atom.tooltips.add(this.element,{title:"<div>"+b+"</div>",delay:250,
html:!0})},handleMouseOut:function(a){this.tooltip.dispose()}});var l=function(){};l.dateStr=function(a){var h=a.getMonth()+1,d=a.getDate(),c=a.getHours(),f=a.getMinutes(),e=a.getSeconds();return a.getFullYear()+"-"+(10>h?"0"+h:""+h)+"-"+(10>d?"0"+d:""+d)+" "+(10>c?"0"+c:""+c)+":"+(10>f?"0"+f:""+f)+":"+(10>e?"0"+e:""+e)};var p=require("atom").CompositeDisposable,k=function(a){var c=this;this.id=setInterval(function(){c.run()},a)};k.prototype={stop:function(){null!=this.id&&(clearInterval(this.id),
this.id=null)},run:function(){}};var m=function(){};m.xTimeAgo=function(a){a=((new Date).getTime()-a.getTime())/1E3;var c=Math.floor(a/86400);return isNaN(c)||0>c||31<=c?null:0==c?60>a?"just now":120>a?"1 minute ago":3600>a?Math.floor(a/60)+" minutes ago":7200>a?"1 hour ago":86400>a?Math.floor(a/3600)+" hours ago":null:1==c?"Yesterday":7>c?c+" days ago":31>c?Math.ceil(c/7)+" weeks ago":null};var n=0;module.exports=a})("undefined"!=typeof console?console:{log:function(){}});
