"v4.0.0">process.version&&console.warn("Module "+("undefined"==typeof module?"":module.filename)+" requires node.js version 4.0.0 or higher");"v4.0.0">process.version&&console.warn("Module "+("undefined"==typeof module?"":module.filename)+" requires node.js version 4.0.0 or higher");
(function(){function e(c,a){if(null==a)return null;null==a.__id__&&(a.__id__=p++);var d;null==c.hx__closures__?c.hx__closures__={}:d=c.hx__closures__[a.__id__];null==d&&(d=function(){return d.method.apply(d.scope,arguments)},d.scope=c,d.method=a,c.hx__closures__[a.__id__]=d);return d}var a=function(){};a.activate=function(c){a.timeStart=new Date;a.disposables=new q;a.view=new k;null==c?a.enable():c.enabled?a.enable():a.disable()};a.serialize=function(){return{enabled:a.enabled}};a.deactivate=function(){null!=
a.timer&&(a.timer.stop(),a.timer=null);a.view.destroy();a.disposables.dispose()};a.enable=function(){a.enabled=!0;null!=a.commandEnable&&a.commandEnable.dispose();a.disposables.add(a.commandDisable=atom.commands.add("atom-workspace","clock:hide",function(c){a.disable()}));a.timer=new m(1E3);a.timer.run=a.update;a.view.show();a.view.setTime(new Date)};a.disable=function(){a.enabled=!1;null!=a.timer&&(a.timer.stop(),a.timer=null);null!=a.commandDisable&&a.commandDisable.dispose();a.disposables.add(a.commandEnable=
atom.commands.add("atom-workspace","clock:show",function(c){a.enable()}));a.view.hide()};a.update=function(){a.view.setTime(new Date)};a.consumeStatusBar=function(c){c.addRightTile({item:a.view.element,priority:-100})};var h=function(){this.element=window.document.createElement("time");this.element.classList.add("status-bar-clock","inline-block");this.showSeconds=atom.config.get("clock.seconds");this.configChangeListener=atom.config.onDidChange("clock",{},e(this,this.handleConfigChange))};h.prototype=
{show:function(){this.element.style.display="inline-block"},hide:function(){this.element.style.display="none"},destroy:function(){this.configChangeListener.dispose();this.element.remove()},setTime:function(c){},handleConfigChange:function(c){}};var k=function(){h.call(this);this.showSeconds=atom.config.get("clock.seconds");this.format24=atom.config.get("clock.format");this.amPmSuffix=atom.config.get("clock.am_pm_suffix");this.setShowIcon(atom.config.get("clock.icon"));this.element.addEventListener("mouseover",
e(this,this.handleMouseOver),!1);this.element.addEventListener("mouseout",e(this,this.handleMouseOut),!1);this.contextMenu=atom.contextMenu.add({".status-bar-clock":[{label:"Hide",command:"clock:hide"}]})};k.__super__=h;k.prototype=function(c,a){function d(){}d.prototype=c;var f=new d,g;for(g in a)f[g]=a[g];a.toString!==Object.prototype.toString&&(f.toString=a.toString);return f}(h.prototype,{setTime:function(a){this.element.dateTime=l.dateStr(a);var b=a.getHours();!this.format24&&12<b&&(b-=12);var b=
(10>b?"0"+b:null==b?"null":""+b)+":",d=a.getMinutes(),b=b+(10>d?"0"+d:null==d?"null":""+d);this.showSeconds&&(d=a.getSeconds(),b+=":"+(10>d?"0"+d:null==d?"null":""+d));!this.format24&&this.amPmSuffix&&(b+=12<a.getHours()?" PM":" AM");this.element.textContent=b},destroy:function(){h.prototype.destroy.call(this);this.element.removeEventListener("mouseover",e(this,this.handleMouseOver));this.element.removeEventListener("mouseout",e(this,this.handleMouseOut));null!=this.tooltip&&this.tooltip.dispose();
this.contextMenu.dispose()},handleConfigChange:function(c){c=c.newValue;this.showSeconds=c.seconds;this.format24=c.format;this.amPmSuffix=c.am_pm_suffix;this.setShowIcon(c.icon);a.enabled&&this.setTime(new Date)},setShowIcon:function(a){a?this.element.classList.add("icon-clock"):this.element.classList.remove("icon-clock")},handleMouseOver:function(c){null!=this.tooltip&&this.tooltip.dispose();c="<div>"+l.dateStr(new Date)+"</div>";c+="<div>This session started: "+n.xTimeAgo(a.timeStart)+"</div>";
this.tooltip=atom.tooltips.add(this.element,{title:"<div>"+c+"</div>",delay:250,html:!0})},handleMouseOut:function(a){this.tooltip.dispose()}});var l=function(){};l.dateStr=function(a){var b=a.getMonth()+1,d=a.getDate(),f=a.getHours(),g=a.getMinutes(),e=a.getSeconds();return a.getFullYear()+"-"+(10>b?"0"+b:""+b)+"-"+(10>d?"0"+d:""+d)+" "+(10>f?"0"+f:""+f)+":"+(10>g?"0"+g:""+g)+":"+(10>e?"0"+e:""+e)};var q=require("atom").CompositeDisposable,m=function(a){var b=this;this.id=setInterval(function(){b.run()},
a)};m.prototype={stop:function(){null!=this.id&&(clearInterval(this.id),this.id=null)},run:function(){}};var n=function(){};n.xTimeAgo=function(a){a=((new Date).getTime()-a.getTime())/1E3;var b=Math.floor(a/86400);return isNaN(b)||0>b||31<=b?null:0==b?60>a?"just now":120>a?"1 minute ago":3600>a?Math.floor(a/60)+" minutes ago":7200>a?"1 hour ago":86400>a?Math.floor(a/3600)+" hours ago":null:1==b?"Yesterday":7>b?b+" days ago":31>b?Math.ceil(b/7)+" weeks ago":null};var p=0;module.exports=a})();
